// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Capstone.FSharp")>]
[<assembly: AssemblyProductAttribute("Capstone.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("Capstone Engine language bindings for F#.")>]
[<assembly: AssemblyVersionAttribute("0.0.6")>]
[<assembly: AssemblyFileVersionAttribute("0.0.6")>]
[<assembly: GuidAttribute("8b18e4e0-376d-4aa8-86ac-4ded5a56305c")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Capstone.FSharp"
    let [<Literal>] AssemblyProduct = "Capstone.FSharp"
    let [<Literal>] AssemblyDescription = "Capstone Engine language bindings for F#."
    let [<Literal>] AssemblyVersion = "0.0.6"
    let [<Literal>] AssemblyFileVersion = "0.0.6"
    let [<Literal>] Guid = "8b18e4e0-376d-4aa8-86ac-4ded5a56305c"
